/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Parent;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-08T17:29:46.360Z")

@Api(value = "parents", description = "the parents API")
public interface ParentsApi {

    @ApiOperation(value = "Create a parent", nickname = "parentsPost", notes = "Returns successfully created parent", response = Parent.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully created parent", response = Parent.class) })
    @RequestMapping(value = "/parents",
        method = RequestMethod.POST)
    ResponseEntity<Parent> parentsPost(@ApiParam(value = "Parent details" ,required=true )  @Valid @RequestBody Parent parent);

}
